import express from 'express';
import authMiddleware from '../../middlewares/authMiddleware';
import adminAuthentication from '../../middlewares/adminAuth';
import PostsControllers from '../../controllers/v1/postsControllers';
import validationMiddleware from '../../middlewares/validator';
import {
  postGifSchemaDTO,
  gifLikeSchemaDTO,
  gifCommentSchemaDTO,
  editGifCommentSchemaDTO,
  deleteGifSchemaDTO,
  fetchAllGifsSchemaDTO,
  fetchUserGifsSchemaDTO,
  fetchGifSchemaDTO,
  fetchGifCommentSchemaDTO,
  deleteGifCommentSchemaDTO,
  postArticleSchemaDTO,
  deleteArticleSchemaDTO,
  fetchAllArticlesSchemaDTO,
  fetchUserArticlesSchemaDTO,
  editArticleSchemaDTO,
  fetchSingleArticleSchemaDTO,
  articleLikeSchemaDTO,
  articleCommentSchemaDTO,
  fetchArticleCommentSchemaDTO,
  editArticleCommentSchemaDTO,
  deleteArticleCommentSchemaDTO,
  fetchAllPostsSchemaDTO,
  fetchCategoryArticleDTO,
} from '../../zodSchema';
import { uploadedGif } from '../../middlewares/multerMiddleware';

const router = express();
const postsControllers = new PostsControllers();

router.post(
  '/post_gif',
  authMiddleware,
  uploadedGif,
  validationMiddleware(postGifSchemaDTO),
  postsControllers.createGifPost
);
router.delete(
  '/gif/delete_gif/:gifId',
  authMiddleware,
  validationMiddleware(deleteGifSchemaDTO),
  postsControllers.deleteGifPost
);
router.delete(
  '/gif/admin_delete_gif/:gifId',
  authMiddleware,
  adminAuthentication,
  validationMiddleware(deleteGifSchemaDTO),
  postsControllers.adminDeleteGifPost
);
router.get(
  '/all_gifs',
  authMiddleware,
  validationMiddleware(fetchAllGifsSchemaDTO),
  postsControllers.fetchAllGifs
);
router.get(
  '/user_gifs/:creatorId/:page',
  authMiddleware,
  validationMiddleware(fetchUserGifsSchemaDTO),
  postsControllers.fetchUserGifs
);
router.get(
  '/gif/:gifId',
  authMiddleware,
  validationMiddleware(fetchGifSchemaDTO),
  postsControllers.fetchGif
);
router.post(
  '/like_gif/:gifId',
  authMiddleware,
  validationMiddleware(gifLikeSchemaDTO),
  postsControllers.likeGif
);
router.post(
  '/gif/comment/:gifId',
  authMiddleware,
  validationMiddleware(gifCommentSchemaDTO),
  postsControllers.commentOnGif
);
router.get(
  '/gif_comments/:gifId/:page',
  authMiddleware,
  validationMiddleware(fetchGifCommentSchemaDTO),
  postsControllers.fetchGifComments
);
router.patch(
  '/gif/edit_comment/:commentId',
  authMiddleware,
  validationMiddleware(editGifCommentSchemaDTO),
  postsControllers.editGifComment
);
router.delete(
  '/gif/delete_comment/:commentId',
  authMiddleware,
  validationMiddleware(deleteGifCommentSchemaDTO),
  postsControllers.deleteGifComment
);
router.delete(
  '/gif/admin_delete_comment/:commentId',
  authMiddleware,
  adminAuthentication,
  validationMiddleware(deleteGifCommentSchemaDTO),
  postsControllers.adminDeleteGifComment
);
router.post(
  '/post_article',
  authMiddleware,
  validationMiddleware(postArticleSchemaDTO),
  postsControllers.postArticle
);
router.patch(
  '/article/edit_article/:articleId',
  authMiddleware,
  validationMiddleware(editArticleSchemaDTO),
  postsControllers.updateArticle
);
router.delete(
  '/article/delete_article/:articleId',
  authMiddleware,
  validationMiddleware(deleteArticleSchemaDTO),
  postsControllers.deleteArticle
);
router.delete(
  '/article/admin_delete_article/:articleId',
  authMiddleware,
  adminAuthentication,
  validationMiddleware(deleteArticleSchemaDTO),
  postsControllers.adminDeleteArticle
);
router.get(
  '/article/all_articles',
  authMiddleware,
  validationMiddleware(fetchAllArticlesSchemaDTO),
  postsControllers.fetchAllArticles
);
router.get(
  '/article/user_articles/:creatorId/:page',
  authMiddleware,
  validationMiddleware(fetchUserArticlesSchemaDTO),
  postsControllers.fetchUserArticles
);
router.get(
  '/article/category_articles/:category/:page',
  authMiddleware,
  validationMiddleware(fetchCategoryArticleDTO),
  postsControllers.fetchCategoryArticle
);
router.get(
  '/article/:articleId',
  authMiddleware,
  validationMiddleware(fetchSingleArticleSchemaDTO),
  postsControllers.fetchSingleArticle
);
router.post(
  '/like_article/:articleId',
  authMiddleware,
  validationMiddleware(articleLikeSchemaDTO),
  postsControllers.likeArticle
);
router.post(
  '/article/comment/:articleId',
  authMiddleware,
  validationMiddleware(articleCommentSchemaDTO),
  postsControllers.commentOnArticle
);
router.get(
  '/article_comments/:articleId/:page',
  authMiddleware,
  validationMiddleware(fetchArticleCommentSchemaDTO),
  postsControllers.fetchArticleComments
);
router.patch(
  '/article/edit_comment/:commentId',
  authMiddleware,
  validationMiddleware(editArticleCommentSchemaDTO),
  postsControllers.editArticleComment
);
router.delete(
  '/article/delete_comment/:commentId',
  authMiddleware,
  validationMiddleware(deleteArticleCommentSchemaDTO),
  postsControllers.deleteArticleComment
);
router.delete(
  '/article/admin_delete_comment/:commentId',
  authMiddleware,
  adminAuthentication,
  validationMiddleware(deleteArticleCommentSchemaDTO),
  postsControllers.adminDeleteArticleComment
);
router.get(
  '/feed',
  authMiddleware,
  validationMiddleware(fetchAllPostsSchemaDTO),
  postsControllers.fetchAllPosts
);

export default router;
