/* Replace with your SQL commands */

ALTER TABLE IF EXISTS public.gif_comments
ADD COLUMN IF NOT EXISTS "comment_id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 );